Add gitpod support for puppet modules
puppetlabs/pdk-templates pull request #354
Opened 2020-10-17 19:53 UTC by logicminds

* This adds initial support for gipod puppet development.  Any user
    who opens the module in gitpod would automatically
    stand up a pdk and puppet development environment.

    While this is a first stab at this file I expect further customizations
    to follow and allow the user to utilize the sync or config_defaults
    to tweak their own unique gitpod.

    I decided to leave the clickable banner that normally goes in the readme out of this changeset as I don't know
    what the user's gitpod link would actually be.  I am sure a config variable might help with this but decided to KISS.

2020-10-19 15:24 UTC, michaeltlombardi commented
We're discussing this one internally a bit, as it will effect _all_ Puppet modules. :)

2020-10-20 01:26 UTC, logicminds commented
Yes similar to Travis, appveyor and other stuff people ignore if they don't use.

2020-11-09 08:59 UTC, DavidS requested changes
I'm happy to merge this, if we tag this as `unmanaged: true` in the config defaults. That way the functionality is there for people who want it.

> other stuff people ignore if they don't use
We've heard enough complaints about the confusing maze of files we deploy for newcomers that I don't want to add on top of that.
I'd disable all non-essential stuff too for a pdk 2.0 release.

@binford2k once we get this merged, I suggest we enable it on all supported modules to see if that brings in more/better contributions.

2020-11-11 03:40 UTC, logicminds commented
@DavidS made the changes as requested and updated the README as well to show how to enable.

2020-11-16 08:56 UTC, DavidS approved these changes

2020-11-16 08:56 UTC, merged