Update Github Actions auto_release workflow
puppetlabs/pdk-templates pull request #394
Opened 2021-02-04 15:24 UTC by carabasdaniel

2021-02-04 16:06 UTC, carabasdaniel commented
Successful workflow run: https://github.com/puppetlabs/puppetlabs-testing/runs/1832174668?check_suite_focus=true
Resulting PR: https://github.com/puppetlabs/puppetlabs-testing/pull/343

2021-02-04 18:19 UTC, sanfrancrisko approved these changes

2021-02-05 09:57 UTC, david22swan approved these changes

2021-02-05 10:19 UTC, merged

2021-02-05 10:24 UTC, DavidS requested changes

2021-02-05 10:24 UTC, DavidS commented on moduleroot/.github/workflows/auto_release.yml.erb
>          echo "::set-output name=ver::$(cat metadata.json | jq .version)"
```suggestion
        echo "::set-output name=ver::$(cat metadata.json | jq .version | tr -d \")"
```

remove additional quotes from result:

![2021-02-05_10MS+0000_444x126](https://user-images.githubusercontent.com/27712/107020360-affab600-679a-11eb-8981-950dde491be0.png)

2021-02-05 10:24 UTC, DavidS commented on moduleroot/.github/workflows/auto_release.yml.erb
> +        title: "Release prep v${{ steps.gv.outputs.ver }}"
```suggestion
        title: "Release prep v${{ steps.gv.outputs.ver }}"
        body: "Automated release-prep through [pdk-templates](https://github.com/puppetlabs/pdk-templates/blob/main/moduleroot/.github/workflows/auto_release.yml.erb)"
```

Avoid advertising for others when we can advertise for our own stuff.

2021-02-05 10:24 UTC, DavidS commented on moduleroot/.github/workflows/auto_release.yml.erb
>          branch: "release-prep"
```suggestion
        branch: "release-prep"
        delete-branch: true
```

clean up afterwards

2021-02-05 10:24 UTC, DavidS commented on moduleroot/.github/workflows/auto_release.yml.erb
> +        title: "Release prep v${{ steps.gv.outputs.ver }}"
extra points for extracting the generated changelog bits of this release and add them to the text here.