Use different providers in Github Action workflows matrix
puppetlabs/pdk-templates pull request #398
Opened 2021-02-11 14:07 UTC by carabasdaniel

2021-02-12 11:20 UTC, carabasdaniel commented
Example run: https://github.com/puppetlabs/puppetlabs-testing/actions/runs/560828493

2021-02-17 09:55 UTC, DavidS requested changes

2021-02-17 09:55 UTC, DavidS commented on moduleroot/.github/workflows/nightly.yml.erb
> +    name: "${{matrix.platforms.label}}-${{matrix.collection}}"
```suggestion
    name: "${{matrix.platforms.label}}, ${{matrix.collection}}"
```

2021-02-18 10:18 UTC, sheenaajay approved these changes

2021-02-18 10:47 UTC, DavidS approved these changes

2021-02-18 10:47 UTC, DavidS commented
so this is only waiting for a litmus release now?

2021-02-18 14:10 UTC, carabasdaniel commented
After the litmus release that contains the new matrix_from_metadata_v2 script, one more PDK Sync run will allow us update all our supported modules to use docker containers in the acceptance matrix.

2021-02-24 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/pdk-templates?pullRequest=398) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/pdk-templates?pullRequest=398) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/pdk-templates?pullRequest=398) it.</sub>

2021-02-25 13:37 UTC, merged